CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE = arm-none-eabi-size

STM32CUBEPROG:= ../../../stmcubeprog/bin/STM32_Programmer.sh -vb 1 -q -c port=SWD 
GNUGCC = ../../../gcc-arm-none-eabi/bin
# CC = $(GNUGCC)/arm-none-eabi-gcc
# OBJCOPY = $(GNUGCC)/arm-none-eabi-objcopy
# SIZE =  $(GNUGCC)/arm-none-eabi-size
